# config file containing credentials for RDS MYSQL instance , S3

# example with HANK's code
rds:
  bobsim_schema:
    username: "admin"
    password: "bobsim2020"
    url: "production-bobsim-aurora.cluster-cm9kakdihdlv.ap-northeast-2.rds.amazonaws.com"

  public_data:
    username: "admin"
    password: "bobsim2020"
    url: "production-bobsim-aurora.cluster-cm9kakdihdlv.ap-northeast-2.rds.amazonaws.com"


s3:
  url: "https://introtodatascience5.s3.ap-northeast-2.amazonaws.com"
  bucket: "introtodatascience5"

open_api:
  emergency_data:
    service_key: "rdmH5XR5ycW9emHC9D56bNydZrvc6546Z0fxlqCdCPc4RpWZ99GMoGoRIKRabGJKz2WFcTwN9ekSTfCvzzhiYA=="
    end_point: "http://apis.data.go.kr/B552657/ErmctInfoInqireService/getEmrrmRltmUsefulSckbdInfoInqire?"
